import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Link} from "@mui/material";


const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Home page</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <Link href="/"><a>My App</a></Link>
                </h1>


            </main>
        </div>
    )
}



export default Home
